package exceptions.rest.verification;

/**
 * Error codes that can be generated by the rest layer
 */
public enum RequestErrorCodes {
    INVALID_REQUEST,
    MISSING_COMMON_REQUEST_PARAMS,
    UNEXPECTED_SYSTEM_ERROR
}
